name: Publish Widget
on: workflow_dispatch
env:
  WIDGET_VAL_URL: ${{ secrets.WIDGET_VAL_URL }}
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Generate Widget
        run: node ./scripts/generate_widget.js
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: './output/widget.json'
